### ISSUE TITLE
Import libraries error

### ISSUE THREAD

**Issue by AngSin** [hama/react-native-sinch#1]
Hi Hama,

Thanks for this upload I've been trying really hard to get sinch to work. 

I used your npm package and linked it by running the "react-native link react-native-sinch" command but I still get the following error: 
![screen shot 2017-11-14 at 01 21 58](https://user-images.githubusercontent.com/30783941/32752488-681d203c-c8da-11e7-85e0-5c807c8a059e.png)

Can you please help me?

Best,
Angad

**Comment by AngSin** [comment]
I moved the framework file into the frameworks and that seemed to have solved the issue. However, I still cannot send an sms. 

Here is my code: 
import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';

var RNSinch = require('react-native-sinch');
var custom = "A custom string to be sent to your server backend, through Sinch's callback URL";
RNSinch.init('sinch');

export default class App extends Component<{}> {
  constructor(props) {
    super(props);
    this.state = {
      status: 'unmounted'
    }
  }
  componentDidMount() {
    this.setState({ status: 'mounted' });
    RNSinch.sms('50764660', custom, (err, res) => {
    if (!err) {
      this.setState({ status: err });
    }
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit App.js
        </Text>
        <Text style={styles.instructions}>
          {this.state.status}
        </Text>
      </View>
    );
  }
}

**Comment by hama** [comment]
`RNSinch.init('sinch');`

Did you set the right app key ?

**Comment by AngSin** [comment]
Hi yes, I did. But I'm gonna close this because I started to use Twilio instead of Sinch.
